-- Add sample job data to test the application
INSERT INTO public.jobs (
  title,
  company,
  company_logo,
  description,
  requirements,
  benefits,
  salary_min,
  salary_max,
  location,
  job_type,
  experience_level,
  skills_required,
  is_active
) VALUES
(
  'Senior Frontend Developer',
  'TechCorp Inc.',
  'https://via.placeholder.com/100x100?text=TC',
  'We are looking for an experienced Frontend Developer to join our dynamic team. You''ll be working on cutting-edge web applications using React, TypeScript, and modern development practices.',
  ARRAY['5+ years React experience', 'TypeScript proficiency', 'Modern CSS/SCSS', 'Testing frameworks'],
  ARRAY['Health insurance', 'Remote work', 'Stock options', 'Learning budget'],
  120000,
  160000,
  'San Francisco, CA',
  'full-time',
  'senior',
  ARRAY['React', 'TypeScript', 'JavaScript', 'CSS', 'HTML'],
  true
),
(
  'Full Stack Engineer',
  'StartupXYZ',
  'https://via.placeholder.com/100x100?text=SX',
  'Join our growing startup as a Full Stack Engineer. You''ll work across the entire technology stack, from React frontends to Node.js backends and cloud infrastructure.',
  ARRAY['React/Node.js experience', 'Database design', 'API development', 'Cloud platforms'],
  ARRAY['Equity package', 'Flexible hours', 'Remote first', 'Conference budget'],
  100000,
  140000,
  'Remote',
  'full-time',
  'mid',
  ARRAY['React', 'Node.js', 'TypeScript', 'AWS', 'PostgreSQL'],
  true
),
(
  'UI/UX Designer',
  'Design Studio',
  'https://via.placeholder.com/100x100?text=DS',
  'We''re seeking a talented UI/UX Designer to create beautiful, user-friendly interfaces for our clients. Experience with Figma and modern design systems required.',
  ARRAY['Figma proficiency', 'Design systems', 'User research', 'Prototyping'],
  ARRAY['Creative freedom', 'Design conferences', 'Hardware budget', 'Flexible schedule'],
  80000,
  100000,
  'New York, NY',
  'contract',
  'mid',
  ARRAY['Figma', 'UI Design', 'UX Design', 'Prototyping', 'Design Systems'],
  true
),
(
  'DevOps Engineer',
  'CloudTech Solutions',
  'https://via.placeholder.com/100x100?text=CT',
  'Looking for a DevOps Engineer to help scale our infrastructure and improve our deployment processes. Experience with Kubernetes and CI/CD pipelines essential.',
  ARRAY['Kubernetes experience', 'CI/CD pipelines', 'Infrastructure as Code', 'Monitoring tools'],
  ARRAY['Learning budget', 'Remote work', 'Performance bonus', 'Health benefits'],
  110000,
  150000,
  'Austin, TX',
  'full-time',
  'senior',
  ARRAY['Kubernetes', 'Docker', 'AWS', 'Terraform', 'Jenkins'],
  true
),
(
  'Product Manager',
  'InnovateNow',
  'https://via.placeholder.com/100x100?text=IN',
  'We''re looking for a Product Manager to drive our product strategy and work closely with engineering and design teams to deliver amazing user experiences.',
  ARRAY['Product strategy', 'Agile methodologies', 'User research', 'Analytics'],
  ARRAY['Stock options', 'Product conference budget', 'Flexible PTO', 'Team retreats'],
  130000,
  170000,
  'Seattle, WA',
  'full-time',
  'senior',
  ARRAY['Product Management', 'Agile', 'Analytics', 'User Research', 'Strategy'],
  true
),
(
  'Data Scientist',
  'DataCorp',
  'https://via.placeholder.com/100x100?text=DC',
  'Join our data science team to build machine learning models and extract insights from large datasets. Experience with Python and ML frameworks required.',
  ARRAY['Python/R proficiency', 'Machine learning', 'Statistics', 'Data visualization'],
  ARRAY['Research time', 'Conference attendance', 'GPU workstation', 'Flexible hours'],
  115000,
  155000,
  'Boston, MA',
  'full-time',
  'mid',
  ARRAY['Python', 'Machine Learning', 'Statistics', 'SQL', 'TensorFlow'],
  true
);